/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.workflow.presentation.views;

import co.unicauca.workflow.access.Factory;
import co.unicauca.workflow.access.IFormatoARepository;
import co.unicauca.workflow.domain.entities.FormatoA;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import co.unicauca.workflow.domain.entities.FormatoA;
import co.unicauca.workflow.domain.entities.enumModalidad;
import co.unicauca.workflow.domain.service.FormatoAService;
import co.unicauca.workflow.domain.service.UserService;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.time.ZoneId;


/**
 *
 * @author Usuario
 */
public class AdjuntarDocumentos extends javax.swing.JPanel {
    
    IFormatoARepository repoFomratoA = Factory.getInstance().getFormatoARepository("default");
    FormatoAService serviceFormato = new FormatoAService(repoFomratoA);
    
    
    private FormatoA formatoA;
    /**
     * Creates new form AdjuntarDocumentos
     */
    public AdjuntarDocumentos(FormatoA formatoA) {
        this.formatoA = formatoA;
        initComponents(); 
        initStyles();
        
        // Habilitar carta laboral solo si es práctica laboral
        if (formatoA.getMode() != enumModalidad.PRACTICA_PROFESIONAL) {
            btCarta.setEnabled(false);
        }
        
        
    }
    
    private void initStyles(){
        
        // Look and Feel moderno
       FlatMTMaterialLighterIJTheme.setup();

       txtRutaPDF.setForeground(new Color(30, 144, 255)); // azul moderno
       txtRutaCarta.setForeground(new Color(30, 144, 255));

       // Botones redondeados
       btPDF.putClientProperty("JButton.buttonType", "roundRect");
       btCarta.putClientProperty("JButton.buttonType", "roundRect");
       btnGuardar.putClientProperty("JButton.buttonType", "roundRect");

       // Estilo para el calendario
       dateChooser.getCalendarButton().putClientProperty("JButton.buttonType", "roundRect");
       ((JTextField) dateChooser.getDateEditor().getUiComponent())
               .setBackground(Color.WHITE);
       ((JTextField) dateChooser.getDateEditor().getUiComponent())
               .setBorder(javax.swing.BorderFactory.createLineBorder(new Color(30, 144, 255)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btPDF = new javax.swing.JButton();
        txtRutaPDF = new javax.swing.JLabel();
        btCarta = new javax.swing.JButton();
        txtRutaCarta = new javax.swing.JLabel();
        lblClendario = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(646, 530));

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btPDF.setText("Adjunte un PDF");
        btPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btPDFMousePressed(evt);
            }
        });

        txtRutaPDF.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRutaPDF.setForeground(new java.awt.Color(51, 51, 255));
        txtRutaPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRutaPDF.setText("Ruta");

        btCarta.setText("Adjunte un PDF");
        btCarta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCartaMouseClicked(evt);
            }
        });

        txtRutaCarta.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRutaCarta.setForeground(new java.awt.Color(51, 51, 255));
        txtRutaCarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRutaCarta.setText("Ruta");

        lblClendario.setBackground(new java.awt.Color(0, 0, 0));
        lblClendario.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblClendario.setForeground(new java.awt.Color(0, 0, 0));
        lblClendario.setText("Seleccionar fecha de publicacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(txtRutaPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCarta, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(txtRutaCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblClendario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRutaPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btCarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRutaCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblClendario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(195, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if (dateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha.");
            return;
        }
        LocalDate fechaSeleccionada = dateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        formatoA.setDate(fechaSeleccionada);

        
        boolean ok = serviceFormato.subirFormatoA(formatoA);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Formato A actualizado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el Formato A.");
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btPDFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPDFMousePressed
        JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Seleccionar archivo PDF");

            // Filtro para solo mostrar PDFs
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
            fileChooser.setFileFilter(filtro);

            int resultado = fileChooser.showOpenDialog(this);

            if (resultado == JFileChooser.APPROVE_OPTION) {
                File archivoSeleccionado = fileChooser.getSelectedFile();

                try {
                    // Ruta de destino dentro del proyecto
                    String carpetaDestino = System.getProperty("user.dir") + File.separator + "archivosPDF";
                    File directorio = new File(carpetaDestino);
                    if (!directorio.exists()) {
                        directorio.mkdir(); // crea la carpeta si no existe
                    }

                    // Copiar el archivo al destino
                    File archivoDestino = new File(carpetaDestino, archivoSeleccionado.getName());
                    Files.copy(archivoSeleccionado.toPath(), archivoDestino.toPath(), StandardCopyOption.REPLACE_EXISTING);

                    // Guardar la ruta en el objeto FormatoA
                    String rutaGuardada = archivoDestino.getAbsolutePath();
                    formatoA.setArchivoPDF(rutaGuardada);
                    txtRutaPDF.setText(rutaGuardada);

                    JOptionPane.showMessageDialog(this, "Archivo guardado en: " + rutaGuardada);

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
                }
        }
    }//GEN-LAST:event_btPDFMousePressed

    private void btCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCartaMouseClicked
        JFileChooser fileChooser = new JFileChooser();
           fileChooser.setDialogTitle("Seleccionar carta laboral (PDF)");

           // Filtro para solo mostrar PDFs
           FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
           fileChooser.setFileFilter(filtro);

           int resultado = fileChooser.showOpenDialog(this);

           if (resultado == JFileChooser.APPROVE_OPTION) {
               File archivoSeleccionado = fileChooser.getSelectedFile();

               try {
                   // Ruta de destino dentro del proyecto
                   String carpetaDestino = System.getProperty("user.dir") + File.separator + "archivosPDF";
                   File directorio = new File(carpetaDestino);
                   if (!directorio.exists()) {
                       directorio.mkdir(); // crea la carpeta si no existe
                   }

                   // Copiar el archivo al destino
                   File archivoDestino = new File(carpetaDestino, archivoSeleccionado.getName());
                   Files.copy(archivoSeleccionado.toPath(), archivoDestino.toPath(), StandardCopyOption.REPLACE_EXISTING);

                   // Guardar la ruta en el objeto FormatoA
                   String rutaGuardada = archivoDestino.getAbsolutePath();
                   formatoA.setCartaLaboral(rutaGuardada);
                   txtRutaCarta.setText(rutaGuardada);

                   JOptionPane.showMessageDialog(this, "Archivo guardado en: " + rutaGuardada);

               } catch (IOException ex) {
                   JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
               }
           }
    }//GEN-LAST:event_btCartaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCarta;
    private javax.swing.JButton btPDF;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClendario;
    private javax.swing.JLabel txtRutaCarta;
    private javax.swing.JLabel txtRutaPDF;
    // End of variables declaration//GEN-END:variables
}
