/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.workflow.presentation.views;

import co.unicauca.workflow.access.Factory;
import co.unicauca.workflow.access.IFormatoARepository;
import co.unicauca.workflow.domain.entities.FormatoA;
import co.unicauca.workflow.domain.entities.enumModalidad;
import co.unicauca.workflow.domain.service.FormatoAService;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.time.ZoneId;
import javax.swing.UIManager;


/**
 *
 * @author Usuario
 */
public class AdjuntarDocumentos extends javax.swing.JPanel {
    
    IFormatoARepository repoFomratoA = Factory.getInstance().getFormatoARepository("default");
    FormatoAService serviceFormato = new FormatoAService(repoFomratoA);
    
    
    private FormatoA formatoA;
    /**
     * Creates new form AdjuntarDocumentos
     */
    public AdjuntarDocumentos(FormatoA formatoA) {
        this.formatoA = formatoA;
        initComponents();
        initStyles();

        dateChooser.setMinSelectableDate(java.sql.Date.valueOf(LocalDate.now()));
       
        
        // Habilitar carta laboral solo si es práctica laboral
        if (formatoA.getMode() != enumModalidad.PRACTICA_PROFESIONAL) {
            btCarta.setEnabled(false);
        }
        
        
    }
    
   private void initStyles() {

    // Look and Feel moderno
    FlatMTMaterialLighterIJTheme.setup();

    txtRutaPDF.setForeground(new Color(30, 144, 255)); // azul moderno
    txtRutaCarta.setForeground(new Color(30, 144, 255));

    // Botones redondeados
    btPDF.putClientProperty("JButton.buttonType", "roundRect");
    btCarta.putClientProperty("JButton.buttonType", "roundRect");
    btnGuardar.putClientProperty("JButton.buttonType", "roundRect");

    // Estilo para el calendario: botón
    dateChooser.getCalendarButton().putClientProperty("JButton.buttonType", "roundRect");

    // Campo de texto del calendario
      // Campo de texto del calendario
    ((JTextField) dateChooser.getDateEditor().getUiComponent())
            .setBackground(Color.WHITE);
    ((JTextField) dateChooser.getDateEditor().getUiComponent())
            .setBorder(javax.swing.BorderFactory.createLineBorder(new Color(30, 144, 255)));

    // 🔹 Colores del popup del calendario (JXMonthView)
    UIManager.put("JXMonthView.background", Color.WHITE);               // Fondo
    UIManager.put("JXMonthView.foreground", Color.BLACK);               // Texto normal
    UIManager.put("JXMonthView.selectionBackground", new Color(200, 230, 255)); // Azul muy suave
    UIManager.put("JXMonthView.selectionForeground", Color.BLACK);      // Texto selección
    UIManager.put("JXMonthView.daysOfTheWeekForeground", Color.DARK_GRAY);
    UIManager.put("JXMonthView.unselectableDayForeground", Color.GRAY);

    // 🔹 Actualizar la UI para que tome inmediatamente los cambios
    javax.swing.SwingUtilities.updateComponentTreeUI(this);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btPDF = new javax.swing.JButton();
        txtRutaPDF = new javax.swing.JLabel();
        btCarta = new javax.swing.JButton();
        txtRutaCarta = new javax.swing.JLabel();
        lblClendario = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(646, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(51, 51, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 422, 112, 37));

        btPDF.setBackground(new java.awt.Color(102, 102, 255));
        btPDF.setText("Adjunte un PDF");
        btPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btPDFMousePressed(evt);
            }
        });
        jPanel1.add(btPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 447, -1));

        txtRutaPDF.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRutaPDF.setForeground(new java.awt.Color(51, 51, 255));
        txtRutaPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRutaPDF.setText("Ruta");
        txtRutaPDF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtRutaPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 447, 25));

        btCarta.setBackground(new java.awt.Color(102, 102, 255));
        btCarta.setText("Adjunte un PDF");
        btCarta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCartaMouseClicked(evt);
            }
        });
        jPanel1.add(btCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 447, -1));

        txtRutaCarta.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRutaCarta.setForeground(new java.awt.Color(51, 51, 255));
        txtRutaCarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRutaCarta.setText("Ruta");
        txtRutaCarta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtRutaCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 447, 25));

        lblClendario.setBackground(new java.awt.Color(0, 0, 0));
        lblClendario.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblClendario.setForeground(new java.awt.Color(0, 0, 0));
        lblClendario.setText("Fecha de publicacion");
        jPanel1.add(lblClendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 406, -1, -1));

        dateChooser.setBackground(new java.awt.Color(153, 153, 153));
        dateChooser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateChooser.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 431, 150, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Carta de aprobacion laboral");
        jLabel1.setMaximumSize(new java.awt.Dimension(112, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(112, 19));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PDF - Formato A");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 162, 532, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if (dateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha.");
            return;
        }
        LocalDate fechaSeleccionada = dateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        formatoA.setDate(fechaSeleccionada);

        
        boolean ok = serviceFormato.subirFormatoA(formatoA);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Formato A actualizado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el Formato A.");
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btPDFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPDFMousePressed
        JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Seleccionar archivo PDF");

            // Filtro para solo mostrar PDFs
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
            fileChooser.setFileFilter(filtro);

            int resultado = fileChooser.showOpenDialog(this);

            if (resultado == JFileChooser.APPROVE_OPTION) {
                File archivoSeleccionado = fileChooser.getSelectedFile();

                try {
                    // Ruta de destino dentro del proyecto
                    String carpetaDestino = System.getProperty("user.dir") + File.separator + "archivosPDF";
                    File directorio = new File(carpetaDestino);
                    if (!directorio.exists()) {
                        directorio.mkdir(); // crea la carpeta si no existe
                    }

                    // Copiar el archivo al destino
                    File archivoDestino = new File(carpetaDestino, archivoSeleccionado.getName());
                    Files.copy(archivoSeleccionado.toPath(), archivoDestino.toPath(), StandardCopyOption.REPLACE_EXISTING);

                    // Guardar la ruta en el objeto FormatoA
                    String rutaGuardada = archivoDestino.getAbsolutePath();
                    formatoA.setArchivoPDF(rutaGuardada);
                    txtRutaPDF.setText(rutaGuardada);

                    JOptionPane.showMessageDialog(this, "Archivo guardado en: " + rutaGuardada);

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
                }
        }
    }//GEN-LAST:event_btPDFMousePressed

    private void btCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCartaMouseClicked
       
            if (formatoA.getMode() != enumModalidad.PRACTICA_PROFESIONAL) {
        JOptionPane.showMessageDialog(this,
            "Solo la modalidad 'Práctica Profesional' permite adjuntar carta laboral.");
        return;
    }
        JFileChooser fileChooser = new JFileChooser();
           fileChooser.setDialogTitle("Seleccionar carta laboral (PDF)");

           // Filtro para solo mostrar PDFs
           FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
           fileChooser.setFileFilter(filtro);

           int resultado = fileChooser.showOpenDialog(this);

           if (resultado == JFileChooser.APPROVE_OPTION) {
               File archivoSeleccionado = fileChooser.getSelectedFile();

               try {
                   // Ruta de destino dentro del proyecto
                   String carpetaDestino = System.getProperty("user.dir") + File.separator + "archivosPDF";
                   File directorio = new File(carpetaDestino);
                   if (!directorio.exists()) {
                       directorio.mkdir(); // crea la carpeta si no existe
                   }

                   // Copiar el archivo al destino
                   File archivoDestino = new File(carpetaDestino, archivoSeleccionado.getName());
                   Files.copy(archivoSeleccionado.toPath(), archivoDestino.toPath(), StandardCopyOption.REPLACE_EXISTING);

                   // Guardar la ruta en el objeto FormatoA
                   String rutaGuardada = archivoDestino.getAbsolutePath();
                   formatoA.setCartaLaboral(rutaGuardada);
                   txtRutaCarta.setText(rutaGuardada);

                   JOptionPane.showMessageDialog(this, "Archivo guardado en: " + rutaGuardada);

               } catch (IOException ex) {
                   JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
               }
           }
    }//GEN-LAST:event_btCartaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCarta;
    private javax.swing.JButton btPDF;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClendario;
    private javax.swing.JLabel txtRutaCarta;
    private javax.swing.JLabel txtRutaPDF;
    // End of variables declaration//GEN-END:variables
}
