/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.workflow.presentation.views;

import co.unicauca.workflow.domain.entities.Docente;
import co.unicauca.workflow.domain.entities.FormatoA;
import java.awt.BorderLayout;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class DetallesFormatoA extends javax.swing.JPanel {

    private FormatoA formato;
    private Docente docente;

    // Constructor "temporal"
    public DetallesFormatoA(FormatoA formato, Docente docente) {
        this.formato = formato;
        this.docente = docente;

        // Para no dejar el panel vacío, algo básico:
        setLayout(new BorderLayout());
        add(new JLabel("Vista de detalle (en construcción)"), BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
