/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.workflow.presentation.views;

/**
 *
 * @author User
 */
public class SubirAnteproyecto extends javax.swing.JPanel {

    /**
     * Creates new form SubirFormatoA
     */
    public SubirAnteproyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparatorTitulo = new javax.swing.JSeparator();
        lbModalidad = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblCodirector = new javax.swing.JLabel();
        lblEstudiante1 = new javax.swing.JLabel();
        lblEstudiante2 = new javax.swing.JLabel();
        lbObjGen = new javax.swing.JLabel();
        lblObjetivosEspecificos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btCrear = new javax.swing.JButton();
        jSeparatorTitulo1 = new javax.swing.JSeparator();
        jSeparatorTitulo2 = new javax.swing.JSeparator();
        jSeparatorTitulo3 = new javax.swing.JSeparator();
        jSeparatorTitulo4 = new javax.swing.JSeparator();
        jSeparatorTitulo5 = new javax.swing.JSeparator();
        jSeparatorTitulo6 = new javax.swing.JSeparator();
        jSeparatorTitulo7 = new javax.swing.JSeparator();
        lblUTitulo = new javax.swing.JLabel();
        lblUModalidad = new javax.swing.JLabel();
        lblUDirector = new javax.swing.JLabel();
        lblUCodirector = new javax.swing.JLabel();
        lblUEstudiante1 = new javax.swing.JLabel();
        lblUEstudiante2 = new javax.swing.JLabel();
        lblUObjGen = new javax.swing.JLabel();
        lblUObjEspec = new javax.swing.JLabel();

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(646, 530));
        Contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Titulo");
        lblTitulo.setToolTipText("");
        Contenido.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, -1));
        Contenido.add(jSeparatorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 300, 20));

        lbModalidad.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbModalidad.setForeground(new java.awt.Color(0, 0, 0));
        lbModalidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbModalidad.setText("Modalidad");
        Contenido.add(lbModalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblDirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblDirector.setForeground(new java.awt.Color(0, 0, 0));
        lblDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDirector.setText("Director de proyecto");
        Contenido.add(lblDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblCodirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCodirector.setForeground(new java.awt.Color(0, 0, 0));
        lblCodirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodirector.setText("Codirector de proyecto");
        Contenido.add(lblCodirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        lblEstudiante1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEstudiante1.setForeground(new java.awt.Color(0, 0, 0));
        lblEstudiante1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstudiante1.setText("Estudiante #1");
        Contenido.add(lblEstudiante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblEstudiante2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEstudiante2.setForeground(new java.awt.Color(0, 0, 0));
        lblEstudiante2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstudiante2.setText("Estudiante #2");
        Contenido.add(lblEstudiante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lbObjGen.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbObjGen.setForeground(new java.awt.Color(0, 0, 0));
        lbObjGen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbObjGen.setText("Objetivo General");
        Contenido.add(lbObjGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 125, -1));

        lblObjetivosEspecificos.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblObjetivosEspecificos.setForeground(new java.awt.Color(0, 0, 0));
        lblObjetivosEspecificos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObjetivosEspecificos.setText("Objetivos especificos");
        Contenido.add(lblObjetivosEspecificos, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 125, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Contenido.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 6, 18, 420));

        btCrear.setBackground(new java.awt.Color(51, 51, 255));
        btCrear.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btCrear.setForeground(new java.awt.Color(0, 0, 0));
        btCrear.setText("CREAR");
        btCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCrearMouseClicked(evt);
            }
        });
        Contenido.add(btCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 409, 112, 37));
        Contenido.add(jSeparatorTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 65, 192, 18));
        Contenido.add(jSeparatorTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 192, 18));
        Contenido.add(jSeparatorTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 192, 18));
        Contenido.add(jSeparatorTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 278, 192, 30));
        Contenido.add(jSeparatorTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 192, 18));
        Contenido.add(jSeparatorTitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 192, 18));
        Contenido.add(jSeparatorTitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 310, 18));

        lblUTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblUTitulo.setText("Titulo");
        Contenido.add(lblUTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, -1));

        lblUModalidad.setForeground(new java.awt.Color(51, 51, 51));
        lblUModalidad.setText("Titulo");
        Contenido.add(lblUModalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, -1));

        lblUDirector.setForeground(new java.awt.Color(51, 51, 51));
        lblUDirector.setText("Titulo");
        Contenido.add(lblUDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 190, -1));

        lblUCodirector.setForeground(new java.awt.Color(51, 51, 51));
        lblUCodirector.setText("Titulo");
        Contenido.add(lblUCodirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 190, -1));

        lblUEstudiante1.setForeground(new java.awt.Color(51, 51, 51));
        lblUEstudiante1.setText("Titulo");
        Contenido.add(lblUEstudiante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 190, -1));

        lblUEstudiante2.setForeground(new java.awt.Color(51, 51, 51));
        lblUEstudiante2.setText("Titulo");
        Contenido.add(lblUEstudiante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, -1));

        lblUObjGen.setForeground(new java.awt.Color(51, 51, 51));
        lblUObjGen.setText("Titulo");
        Contenido.add(lblUObjGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 310, 70));

        lblUObjEspec.setForeground(new java.awt.Color(51, 51, 51));
        lblUObjEspec.setText("Titulo");
        Contenido.add(lblUObjEspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 300, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCrearMouseClicked
      
    }//GEN-LAST:event_btCrearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton btCrear;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparatorTitulo;
    private javax.swing.JSeparator jSeparatorTitulo1;
    private javax.swing.JSeparator jSeparatorTitulo2;
    private javax.swing.JSeparator jSeparatorTitulo3;
    private javax.swing.JSeparator jSeparatorTitulo4;
    private javax.swing.JSeparator jSeparatorTitulo5;
    private javax.swing.JSeparator jSeparatorTitulo6;
    private javax.swing.JSeparator jSeparatorTitulo7;
    private javax.swing.JLabel lbModalidad;
    private javax.swing.JLabel lbObjGen;
    private javax.swing.JLabel lblCodirector;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblEstudiante1;
    private javax.swing.JLabel lblEstudiante2;
    private javax.swing.JLabel lblObjetivosEspecificos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUCodirector;
    private javax.swing.JLabel lblUDirector;
    private javax.swing.JLabel lblUEstudiante1;
    private javax.swing.JLabel lblUEstudiante2;
    private javax.swing.JLabel lblUModalidad;
    private javax.swing.JLabel lblUObjEspec;
    private javax.swing.JLabel lblUObjGen;
    private javax.swing.JLabel lblUTitulo;
    // End of variables declaration//GEN-END:variables
}
