/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.workflow.presentation;

//implementar boton cerrar sesion
//implementar subir formato A y consultar respuestas
//puede implememtar el pane para doc respuestas  

import co.unicauca.workflow.presentation.views.Principal;
import co.unicauca.workflow.domain.entities.Persona;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.BorderLayout;
import javax.swing.JPanel;


import co.unicauca.workflow.presentation.views.DatosFormatoA;
import co.unicauca.workflow.presentation.views.ListaFormatosA;

/**
 *
 * @author User
 */
public class GUIMenuDocente extends javax.swing.JFrame {
    
    


    /**
     * Creates new form GUIDocente
     */


    private static Persona personaLogueado;
    
    public GUIMenuDocente (Persona logueado) {
     this.personaLogueado=logueado;
      initStyles();
        initComponents();
        this.setLocationRelativeTo(null);
        initContent();
    }
    

    private void initStyles(){
      FlatMTMaterialLighterIJTheme.setup();
    }
    
    private void showJPanel(JPanel pl){
        pl.setSize(641,498);
        pl.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(pl,BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint(); 

     }
    
    private void initContent(){
        showJPanel( new Principal(personaLogueado));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bakground = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btRegresar = new javax.swing.JButton();
        btnCloseSesion = new javax.swing.JButton();
        btSubirFormatoA = new javax.swing.JButton();
        btSubirAnteproyecto = new javax.swing.JButton();
        btRespuestas = new javax.swing.JButton();
        Contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bakground.setBackground(new java.awt.Color(26, 55, 171));
        Bakground.setPreferredSize(new java.awt.Dimension(919, 510));

        Menu.setBackground(new java.awt.Color(26, 55, 171));
        Menu.setPreferredSize(new java.awt.Dimension(270, 512));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/LogoPequeño.png"))); // NOI18N
        Icon.setText("jLabel2");
        Menu.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 22, 158, -1));

        Titulo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 55, 171));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOCENTE");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btRespuestas.setBackground(new java.awt.Color(65, 55, 171));
        btRespuestas.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btRespuestas.setForeground(new java.awt.Color(255, 255, 255));
        btRespuestas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/file-chart.png"))); // NOI18N
        btRespuestas.setText("Respuestas");
        btRespuestas.setToolTipText("");
        btRespuestas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btRespuestas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btRespuestas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRespuestas.setIconTextGap(7);
        btRespuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRespuestasMouseClicked(evt);
            }
        });

        btSubirFormatoA.setBackground(new java.awt.Color(65, 55, 171));
        btSubirFormatoA.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btSubirFormatoA.setForeground(new java.awt.Color(255, 255, 255));
        btSubirFormatoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/file-chart.png"))); // NOI18N
        btSubirFormatoA.setText("Subir FormatoA");
        btSubirFormatoA.setToolTipText("");
        btSubirFormatoA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btSubirFormatoA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSubirFormatoA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSubirFormatoA.setIconTextGap(7);
        btSubirFormatoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSubirFormatoAMouseClicked(evt);
            }
        });
        Menu.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, -1));

        btRegresar.setBackground(new java.awt.Color(65, 55, 171));
        btRegresar.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/file-chart.png"))); // NOI18N
        btRegresar.setText("Volver");
        btRegresar.setToolTipText("");
        btRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegresar.setIconTextGap(7);
        btRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegresarMouseClicked(evt);
            }
        });
        Menu.add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 270, 64));

        btnCloseSesion.setBackground(new java.awt.Color(65, 55, 171));
        btnCloseSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseSesion.setText("Cerrar Sesión");
        btnCloseSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseSesionActionPerformed(evt);
            }
        });
        Menu.add(btnCloseSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 469, -1, -1));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSubirFormatoA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnCloseSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Icon)
                .addGap(18, 18, 18)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btSubirFormatoA, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseSesion)
                .addGap(33, 33, 33))
        );
        btSubirFormatoA.setBackground(new java.awt.Color(65, 55, 171));
        btSubirFormatoA.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btSubirFormatoA.setForeground(new java.awt.Color(255, 255, 255));
        btSubirFormatoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/file-chart.png"))); // NOI18N
        btSubirFormatoA.setText("Subir FormatoA");
        btSubirFormatoA.setToolTipText("");
        btSubirFormatoA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btSubirFormatoA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSubirFormatoA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSubirFormatoA.setIconTextGap(7);
        btSubirFormatoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSubirFormatoAMouseClicked(evt);
            }
        });
        Menu.add(btSubirFormatoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 64));

        btSubirAnteproyecto.setBackground(new java.awt.Color(65, 55, 171));
        btSubirAnteproyecto.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btSubirAnteproyecto.setForeground(new java.awt.Color(255, 255, 255));
        btSubirAnteproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/file-chart.png"))); // NOI18N
        btSubirAnteproyecto.setText("Subir Anteproyecto");
        btSubirAnteproyecto.setToolTipText("");
        btSubirAnteproyecto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btSubirAnteproyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSubirAnteproyecto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSubirAnteproyecto.setIconTextGap(7);
        btSubirAnteproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSubirAnteproyectoMouseClicked(evt);
            }
        });
        Menu.add(btSubirAnteproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 253, 270, 64));

        btRespuestas.setBackground(new java.awt.Color(65, 55, 171));
        btRespuestas.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btRespuestas.setForeground(new java.awt.Color(255, 255, 255));
        btRespuestas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/file-chart.png"))); // NOI18N
        btRespuestas.setText("Respuestas");
        btRespuestas.setToolTipText("");
        btRespuestas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btRespuestas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btRespuestas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRespuestas.setIconTextGap(7);
        btRespuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRespuestasMouseClicked(evt);
            }
        });
        Menu.add(btRespuestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 317, 270, 64));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(641, 498));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BakgroundLayout = new javax.swing.GroupLayout(Bakground);
        Bakground.setLayout(BakgroundLayout);
        BakgroundLayout.setHorizontalGroup(
            BakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BakgroundLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        BakgroundLayout.setVerticalGroup(
            BakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(BakgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bakground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bakground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btSubirFormatoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSubirFormatoAMouseClicked
       showJPanel( new DatosFormatoA(personaLogueado));
    }//GEN-LAST:event_btSubirFormatoAMouseClicked

    private void btRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarMouseClicked

        GUIMenuPrincipal ventanaPrincipal = new GUIMenuPrincipal(personaLogueado);
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btRegresarMouseClicked

    private void btnCloseSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSesionActionPerformed
        GUILogin login = new GUILogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseSesionActionPerformed

    private void btRespuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRespuestasMouseClicked
        // Crear la vista correcta: ListaFormatosA
        ListaFormatosA vistaDocente = new ListaFormatosA(personaLogueado);

        // Reemplazar el contenido del panel central
        Contenido.removeAll();
        Contenido.setLayout(new BorderLayout());
        Contenido.add(vistaDocente, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_btRespuestasMouseClicked

    private void btSubirAnteproyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSubirAnteproyectoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btSubirAnteproyectoMouseClicked

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       FlatMTMaterialLighterIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuDocente(personaLogueado).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bakground;
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel Icon;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btRespuestas;
    private javax.swing.JButton btSubirAnteproyecto;
    private javax.swing.JButton btSubirFormatoA;
    private javax.swing.JButton btnCloseSesion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
